listen = "127.0.0.1:9000"
tee_type = "cca"
wasm_component_path = "target/wasm32-wasip1/release/cca_appraiser.wasm"
aa_endpoint = "http://127.0.0.1:8006"
# verifier_endpoint = "127.0.0.1:8080"  # optional, only needed for passport mode
